# YAML EXPLANATION FILE #

Name: Mr.Holmes
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++,Java
Python-Version: Python 3 
Original Creator: Sharllan Paulino
Author: Sharllan Paulino
Copyright: (C) 2021-2024 Shxll <shallcontas@gmail.com>
Copyright-Years: 2021,2022,2023,2024
Download: git clone https://github.com/shxll/MrHolmes
Platforms: Linux/MacOS/Termux/Windows
Version: T.G.D-1.0.4
License: GNU General Public License v3.0
